# Generated by Django 4.0 on 2022-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bankaccount_citizen_role_property_citizen_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='discord_name',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
