# Generated by Django 4.0 on 2022-02-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_citizen_discord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(default='personal', max_length=20),
        ),
    ]
