# Generated by Django 4.0 on 2022-02-04 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_bankaccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication time'),
            preserve_default=False,
        ),
    ]
