# Generated by Django 4.0 on 2022-02-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_transaction_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='minecraft_name',
            field=models.CharField(default='no', max_length=16),
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='role',
        ),
        migrations.AddField(
            model_name='citizen',
            name='role',
            field=models.ManyToManyField(to='bank.Role'),
        ),
    ]
