# Generated by Django 4.0 on 2022-02-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bank', '0007_citizen_minecraft_name_remove_citizen_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='askCitizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_name', models.CharField(max_length=50)),
                ('minecraft_name', models.CharField(max_length=16)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.bankaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
    ]
