# Generated by Django 4.0 on 2022-02-15 09:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_askcitizenship'),
    ]

    operations = [
        migrations.AddField(
            model_name='askcitizenship',
            name='country',
            field=django_countries.fields.CountryField(default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='citizen',
            name='country',
            field=django_countries.fields.CountryField(default='no', max_length=2),
        ),
    ]
